
# Flags to be used for compilation
CFLAGS=-Wall -Wextra -Wpedantic

# Source files to be compiled
SRCS=src/main.c

# Name of the compiled executable
TARGET=imageGen


all:
	${CC} ${CFLAGS} ${SRCS} -o ${TARGET}
